### ISSUE TITLE
is this working in react native, i get metro bundle error

### ISSUE THREAD

**Issue by ZeroCool00** [andcards/react-colorizer#88]
`node_modules/react-colorizer/lib/components/Main/components-styled/ColorPickerWrapper.native.js`: Module `styled-components` does not exist in the Haste module map `

```
"react": "16.6.1",
 "react-native": "0.57.7",
"react-colorizer": "^1.1.1",
```

**Comment by rtkhanas** [comment]
It is probably because `styled-components` is listed in the `peerDependencies ` section. Please run `yarn add styled-components` or `npm install styled-components --save`.

**Comment by DeividasBakanas** [comment]
Is there a reason why `styled-components` and `svgs` are declared as `peerDependencies`, but `dependencies`?

**Comment by rtkhanas** [comment]
@DeividasBakanas it could be a wrong decision, but this library works well with `styled-components` v3 and v4 and `svgs` v3 and v4. So I decided to have it peer not to insist on any specific version. For example, to avoid having both `styled-components` v3 and v4 in a bundle.
